spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: Vortexia-Server
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vortexia?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: vortexia
    password: vortexia

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zeeyeh.vortexiaserver.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

vta:
  compayName: Qinloren
  auth:
    token:
      secret: sf5hxJuzqEFnAMnyZYKbzHqTYaKv36EjQmagXR
      expiration: 86400
    verification-code:
      expireTime: 300